default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: facialbook_development

test:
  <<: *default
  database: facialbook_test

production:
  <<: *default
  database: facialbook_production
  username: facialbook
  password: <%= ENV['FACIALBOOK_DATABASE_PASSWORD'] %>
